# Generated by Django 4.2.5 on 2023-09-12 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratings', models.IntegerField()),
                ('comments', models.TextField()),
                ('equipment_name', models.CharField(max_length=32)),
                ('Time_stamp', models.DateField()),
                ('customer', models.CharField(max_length=32)),
            ],
        ),
    ]
